name: Call shared Java checks

on:
  workflow_dispatch:

jobs:
  java-checks:
    uses: vincev20/dcxeng-common-lintingtesting2/.github/workflows/lint-test.yml@81d59b574a9fc23fb8e9e6463eea3a4888466c10
    secrets: inherit
