name: Call shared Java checks

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  java-checks:
    uses: vincev20/dcxeng-common-lintingtesting2/.github/workflows/lint-test.yml@5965bc01978135febb537dd15f2f32875b0cd181
    secrets: inherit
