name: Call shared Java checks

on:
  workflow_dispatch:

jobs:
  java-checks:
    uses: vincev20/dcxeng-common-lintingtesting2/.github/workflows/lint-test.yml@915255b547ebd0f9f05092a045878f086a0b0a78
    secrets: inherit
